### ISSUE TITLE
#backend

### ISSUE THREAD

**Issue by damian0o** [coding-tree/ctpanel-backend#4]
Dodanie pola "description" do modelu tematu.

@kazbag

**Comment by z1gonzo** [comment]
`const topicSchema = new Schema({
  topic: String,
  votes: {type: Number, default: 0},
  addedDate: {type: Date, default: Date.now},
  userAdded: {type: String, default: 'Gall Anonim'},
  usersVote: [{id: String, vote: String}],
  description: {type: String, default: 'brak opisu dla tematu'},
  tags: Array,
});`

Zamykam.
